version: '3'
services:

  # PHP Service
  service1:
    build: service1/
    restart: unless-stopped
    command:  bash -c "php artisan migrate && php -S service1:80 -t public"
    working_dir: /var/www
    depends_on:
      - mariadb
    networks:
      - app-network

  service2:
    build: service2/
    restart: unless-stopped
    command:  bash -c "php -S service2:8000 -t public"
    working_dir: /var/www
    ports:
      - "8000:8000"
    depends_on:
      - service1
    networks:
      - app-network

  # Varnish Service
  varnish:
    image: varnish:6.0.8
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl:ro
    networks:
      - app-network

  # MySQL Service
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
#Volumes
volumes:
  dbdata:
    driver: local
