version: '3'
services:

  # PHP Service
  service1:
    build: service1/
    restart: unless-stopped
    command:  bash -c "php artisan migrate && php -S service1:80 -t public"
    working_dir: /var/www
    depends_on:
      - mariadb

  service2:
    build: service2/
    restart: unless-stopped
    command:  bash -c "php -S service2:80 -t public"
    working_dir: /var/www
    depends_on:
      - service1

  # Varnish Service
  varnish:
    image: varnish:6.0.8
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl:ro

  # MySQL Service
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"